# ProtoTester Configuration File Example
# This file demonstrates all available configuration options

global:
  output_file: "/var/log/prototester.log"  # Output file for results
  log_level: "info"                        # Log level: debug, info, warn, error
  default_count: 5                         # Default number of tests per run
  timeout: "3s"                           # Default timeout for tests
  interval: "1s"                          # Default interval between tests
  json_output: true                        # Use JSON output format

  # InfluxDB configuration for time-series data storage
  influxdb:
    enabled: false                         # Enable InfluxDB output
    url: "http://localhost:8086"           # InfluxDB server URL
    token: "your-influxdb-token"           # InfluxDB authentication token
    organization: "your-org"               # InfluxDB organization
    bucket: "network-monitoring"           # InfluxDB bucket name
    measurement: "network_latency"         # InfluxDB measurement name
    batch_size: 1000                       # Number of points to batch
    flush_interval: "1s"                   # How often to flush data

daemon:
  enabled: false                          # Enable daemon mode
  run_interval: "5m"                      # How often to run test cycles
  output_file: "/var/log/prototester-daemon.log"
  log_file: "/var/log/prototester-daemon.log"
  pid_file: "/var/run/prototester.pid"
  max_log_size: 104857600                 # 100MB in bytes
  rotate_logs: true                       # Enable log rotation
  stop_on_failure: false                  # Continue running even if tests fail
  max_retries: 3                          # Number of retries for failed tests
  retry_interval: "30s"                   # Wait time between retries

tests:
  # Basic connectivity tests
  - name: "Google DNS TCP"
    type: "tcp"
    target_ipv4: "8.8.8.8"
    target_ipv6: "2001:4860:4860::8888"
    port: 53
    count: 10
    timeout: "3s"
    interval: "500ms"
    enabled: true

  - name: "Cloudflare DNS UDP"
    type: "udp"
    target_ipv4: "1.1.1.1"
    target_ipv6: "2606:4700:4700::1111"
    port: 53
    count: 5
    enabled: true

  # ICMP tests
  - name: "Google Ping"
    type: "icmp"
    target_ipv4: "8.8.8.8"
    target_ipv6: "2001:4860:4860::8888"
    count: 10
    size: 64
    enabled: true

  # HTTP tests
  - name: "Google HTTP"
    type: "http"
    target_ipv4: "142.250.191.110"
    target_ipv6: "2607:f8b0:4009:817::200e"
    port: 80
    count: 5
    enabled: true

  - name: "Google HTTPS"
    type: "https"
    target_ipv4: "142.250.191.110"
    target_ipv6: "2607:f8b0:4009:817::200e"
    port: 443
    count: 5
    enabled: true

  # DNS query tests
  - name: "DNS UDP Query"
    type: "dns"
    target_ipv4: "8.8.8.8"
    target_ipv6: "2001:4860:4860::8888"
    port: 53
    dns_protocol: "udp"
    dns_query: "google.com"
    count: 10
    enabled: true

  - name: "DNS TCP Query"
    type: "dns"
    target_ipv4: "8.8.8.8"
    target_ipv6: "2001:4860:4860::8888"
    port: 53
    dns_protocol: "tcp"
    dns_query: "google.com"
    count: 5
    enabled: true

  - name: "DNS over TLS"
    type: "dot"
    target_ipv4: "1.1.1.1"
    target_ipv6: "2606:4700:4700::1111"
    port: 853
    dns_protocol: "dot"
    dns_query: "cloudflare.com"
    count: 3
    enabled: true

  - name: "DNS over HTTPS"
    type: "doh"
    target_ipv4: "1.1.1.1"
    target_ipv6: "2606:4700:4700::1111"
    port: 443
    dns_protocol: "doh"
    dns_query: "cloudflare.com"
    count: 3
    enabled: true

  # Compare mode tests
  - name: "Google Compare"
    type: "compare"
    hostname: "google.com"
    port: 80
    count: 5
    enabled: true

  - name: "DNS Server Compare"
    type: "compare"
    hostname: "dns.google"
    port: 53
    count: 5
    enabled: true

  # IPv4-only test
  - name: "IPv4 Only Test"
    type: "tcp"
    target_ipv4: "8.8.8.8"
    port: 53
    count: 5
    ipv4_only: true
    enabled: true

  # IPv6-only test
  - name: "IPv6 Only Test"
    type: "tcp"
    target_ipv6: "2001:4860:4860::8888"
    port: 53
    count: 5
    ipv6_only: true
    enabled: false  # Disabled by default

  # Custom intervals and timeouts
  - name: "High Frequency Test"
    type: "tcp"
    target_ipv4: "1.1.1.1"
    port: 53
    count: 20
    interval: "100ms"
    timeout: "1s"
    enabled: false  # Disabled by default

  # Performance monitoring
  - name: "Latency Monitor"
    type: "icmp"
    target_ipv4: "8.8.8.8"
    target_ipv6: "2001:4860:4860::8888"
    count: 100
    interval: "1s"
    enabled: false  # Enable for continuous monitoring