// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {tester} from '../models';

export function ClearHistory():Promise<void>;

export function DeleteHistoryEntry(arg1:string):Promise<boolean>;

export function DeleteSavedConfig(arg1:string):Promise<boolean>;

export function EmitVerbose(arg1:string,arg2:string):Promise<void>;

export function ExportHistoryToJSON():Promise<string>;

export function GetDefaultConfig():Promise<main.TestRequest>;

export function GetHistory():Promise<Array<main.HistoryEntry>>;

export function GetHistoryEntry(arg1:string):Promise<main.HistoryEntry>;

export function GetSavedConfig(arg1:string):Promise<main.SavedConfig>;

export function GetSavedConfigs():Promise<Array<main.SavedConfig>>;

export function RunTest(arg1:main.TestRequest):Promise<tester.TestResult>;

export function SaveConfig(arg1:string,arg2:main.TestRequest):Promise<string>;

export function UpdateSavedConfig(arg1:string,arg2:string,arg3:main.TestRequest):Promise<boolean>;
