// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DeleteHistoryEntry(arg1) {
  return window['go']['main']['App']['DeleteHistoryEntry'](arg1);
}

export function DeleteSavedConfig(arg1) {
  return window['go']['main']['App']['DeleteSavedConfig'](arg1);
}

export function EmitVerbose(arg1, arg2) {
  return window['go']['main']['App']['EmitVerbose'](arg1, arg2);
}

export function ExportHistoryToJSON() {
  return window['go']['main']['App']['ExportHistoryToJSON']();
}

export function GetDefaultConfig() {
  return window['go']['main']['App']['GetDefaultConfig']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetHistoryEntry(arg1) {
  return window['go']['main']['App']['GetHistoryEntry'](arg1);
}

export function GetSavedConfig(arg1) {
  return window['go']['main']['App']['GetSavedConfig'](arg1);
}

export function GetSavedConfigs() {
  return window['go']['main']['App']['GetSavedConfigs']();
}

export function RunTest(arg1) {
  return window['go']['main']['App']['RunTest'](arg1);
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function UpdateSavedConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSavedConfig'](arg1, arg2, arg3);
}
